/* ================================================================
   The shop catalogue — the real Vintage Blue range, transcribed from
   the line sheets in the shared Drive (style numbers, colourways,
   fabric composition, fit, lining and size runs) with the front/back
   photography pulled from the same sheets.

   NOTE: prices are placeholders — the line sheets carry no MRP, so a
   flat per-category figure stands in until real pricing lands.
   ================================================================ */

/* Product photography lives in assets2/products, one front/back (and
   sometimes an inside/lining detail) shot per colourway. Globbing
   beats 168 import lines and keeps filenames as the single key. */
const productImages = import.meta.glob('./assets2/products/*.jpg', {
  eager: true,
  import: 'default',
}) as Record<string, string>

function img(file: string): string {
  return productImages[`./assets2/products/${file}`]
}

export type Category = 'denim' | 'shirts' | 'jackets' | 'cargos' | 'pants'
export type ColorFamily = 'Blues' | 'Browns' | 'Neutrals' | 'Greens'

export interface Product {
  id: string
  handle: string
  name: string
  /** The style number off the line sheet, e.g. '9018' or '142-2'. */
  styleNo: string
  price: number
  categories: Category[]
  popular?: boolean
  images: string[]
  description: string
  details: string[]
  sizes: string[]
  /** Line-sheet keywords, shown as chips on the product page. */
  tags: string[]
  /** Style family — Brawny, Hulk, Corduroy Jacket, and so on. */
  type: string
  fit: string
  material: string
  lining?: string
  color: string
  colorFamily: ColorFamily
  inStock: boolean
}

/** Bottoms run on waist sizes, tops on alpha sizes. */
export const WAIST_SIZES = ['30', '32', '34', '36', '38', '40', '42', '44']
export const ALPHA_SIZES = ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL']
export const SIZES = [...WAIST_SIZES, ...ALPHA_SIZES]

/** Style families, used as the shop's Type filter. */
export const TYPES = [
  'Brawny',
  'Hulk',
  'Jazz',
  'Jazz With Fleece',
  'Joggers',
  'Rock',
  'Comfort Cargo',
  'Light Weight Pant',
  'Heavy Pant',
  'Comfort Pant',
  'Corduroy Shirt',
  'Corduroy Shirt With Fleece',
  'Denim Shirt',
  'Corduroy Jacket',
  'Denim Jacket',
  'Denim Fur Jacket',
  'Denim Fleece Jacket',
]

export const FITS = ['Comfort', 'Straight', 'Baggy', 'Super Baggy', 'Comfort Cargos', 'Regular']

export const COLOR_FAMILIES: ColorFamily[] = ['Blues', 'Browns', 'Neutrals', 'Greens']

/** The shop's categories, in nav order. */
export const CATEGORIES: { slug: Category; label: string }[] = [
  { slug: 'denim', label: 'Denim' },
  { slug: 'shirts', label: 'Shirts' },
  { slug: 'jackets', label: 'Jackets' },
  { slug: 'cargos', label: 'Cargos' },
  { slug: 'pants', label: 'Pants' },
]

export const CATEGORY_LABELS: Record<string, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c.label]),
)

export const PRODUCTS: Product[] = [
  {
    id: '1',
    handle: 'comfort-cargo-9018-mouse',
    name: 'Comfort Cargo 9018 — Mouse',
    styleNo: '9018',
    price: 1899,
    categories: ['cargos'],
    popular: true,
    images: [img('comfort-cargo-9018-mouse-front.jpg'), img('comfort-cargo-9018-mouse-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed mouse finish. Style 9018. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9018', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Mouse',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '2',
    handle: 'comfort-cargo-9018-black',
    name: 'Comfort Cargo 9018 — Black',
    styleNo: '9018',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9018-black-front.jpg'), img('comfort-cargo-9018-black-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed black finish. Style 9018. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9018', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '3',
    handle: 'comfort-cargo-9018-dark-grey',
    name: 'Comfort Cargo 9018 — Dark Grey',
    styleNo: '9018',
    price: 1899,
    categories: ['cargos'],
    images: [
      img('comfort-cargo-9018-dark-grey-front.jpg'),
      img('comfort-cargo-9018-dark-grey-back.jpg'),
    ],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed dark grey finish. Style 9018. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9018', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Dark Grey',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '4',
    handle: 'comfort-cargo-9018-olive',
    name: 'Comfort Cargo 9018 — Olive',
    styleNo: '9018',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9018-olive-front.jpg'), img('comfort-cargo-9018-olive-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed olive finish. Style 9018. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9018', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '5',
    handle: 'comfort-cargo-9018-light-olive',
    name: 'Comfort Cargo 9018 — Light Olive',
    styleNo: '9018',
    price: 1899,
    categories: ['cargos'],
    images: [
      img('comfort-cargo-9018-light-olive-front.jpg'),
      img('comfort-cargo-9018-light-olive-back.jpg'),
    ],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed light olive finish. Style 9018. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9018', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Light Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '6',
    handle: 'comfort-cargo-9018-cream',
    name: 'Comfort Cargo 9018 — Cream',
    styleNo: '9018',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9018-cream-front.jpg'), img('comfort-cargo-9018-cream-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed cream finish. Style 9018. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9018', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Cream',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '7',
    handle: 'comfort-cargo-9019-black',
    name: 'Comfort Cargo 9019 — Black',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-black-front.jpg'), img('comfort-cargo-9019-black-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed black finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '8',
    handle: 'comfort-cargo-9019-grey',
    name: 'Comfort Cargo 9019 — Grey',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-grey-front.jpg'), img('comfort-cargo-9019-grey-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed grey finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Grey',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '9',
    handle: 'comfort-cargo-9019-cream',
    name: 'Comfort Cargo 9019 — Cream',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-cream-front.jpg'), img('comfort-cargo-9019-cream-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed cream finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Cream',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '10',
    handle: 'comfort-cargo-9019-coffee',
    name: 'Comfort Cargo 9019 — Coffee',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-coffee-front.jpg'), img('comfort-cargo-9019-coffee-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed coffee finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Coffee',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '11',
    handle: 'comfort-cargo-9019-navy',
    name: 'Comfort Cargo 9019 — Navy',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    popular: true,
    images: [img('comfort-cargo-9019-navy-front.jpg'), img('comfort-cargo-9019-navy-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed navy finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '12',
    handle: 'comfort-cargo-9019-khaki',
    name: 'Comfort Cargo 9019 — Khaki',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-khaki-front.jpg'), img('comfort-cargo-9019-khaki-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed khaki finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Khaki',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '13',
    handle: 'comfort-cargo-9019-olive',
    name: 'Comfort Cargo 9019 — Olive',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-olive-front.jpg'), img('comfort-cargo-9019-olive-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed olive finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '14',
    handle: 'comfort-cargo-9019-stone',
    name: 'Comfort Cargo 9019 — Stone',
    styleNo: '9019',
    price: 1899,
    categories: ['cargos'],
    images: [img('comfort-cargo-9019-stone-front.jpg'), img('comfort-cargo-9019-stone-back.jpg')],
    description:
      'A comfort-fit cargo in 100% cotton, with utility pockets down the leg and a washed stone finish. Style 9019. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 9019', '100% Cotton', 'Comfort Cargos fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rugged', 'Durable', 'Modern', 'Trendy', 'Functional', 'Premium'],
    type: 'Comfort Cargo',
    fit: 'Comfort Cargos',
    material: '100% Cotton',
    color: 'Stone',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '15',
    handle: 'light-weight-pant-4037-light-grey',
    name: 'Bolster Light Weight Pant — Light Grey',
    styleNo: '4037',
    price: 1699,
    categories: ['pants'],
    images: [
      img('light-weight-pant-4037-light-grey-front.jpg'),
      img('light-weight-pant-4037-light-grey-back.jpg'),
    ],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in light grey. Style 4037. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4037', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Light Weight Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Light Grey',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '16',
    handle: 'light-weight-pant-4035-khaki',
    name: 'Bolster Light Weight Pant — Khaki',
    styleNo: '4035',
    price: 1699,
    categories: ['pants'],
    popular: true,
    images: [
      img('light-weight-pant-4035-khaki-front.jpg'),
      img('light-weight-pant-4035-khaki-back.jpg'),
    ],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in khaki. Style 4035. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4035', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Light Weight Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Khaki',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '17',
    handle: 'light-weight-pant-4037-cream',
    name: 'Bolster Light Weight Pant — Cream',
    styleNo: '4037',
    price: 1699,
    categories: ['pants'],
    images: [
      img('light-weight-pant-4037-cream-front.jpg'),
      img('light-weight-pant-4037-cream-back.jpg'),
    ],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in cream. Style 4037. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4037', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Light Weight Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Cream',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '18',
    handle: 'light-weight-pant-4035-navy',
    name: 'Bolster Light Weight Pant — Navy',
    styleNo: '4035',
    price: 1699,
    categories: ['pants'],
    images: [
      img('light-weight-pant-4035-navy-front.jpg'),
      img('light-weight-pant-4035-navy-back.jpg'),
    ],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in navy. Style 4035. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4035', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Light Weight Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '19',
    handle: 'light-weight-pant-4035-pista',
    name: 'Bolster Light Weight Pant — Pista',
    styleNo: '4035',
    price: 1699,
    categories: ['pants'],
    images: [
      img('light-weight-pant-4035-pista-front.jpg'),
      img('light-weight-pant-4035-pista-back.jpg'),
    ],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in pista. Style 4035. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4035', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Light Weight Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Pista',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '20',
    handle: 'heavy-pant-4036-black',
    name: 'Bolster Heavy Pant — Black',
    styleNo: '4036',
    price: 1699,
    categories: ['pants'],
    images: [img('heavy-pant-4036-black-front.jpg'), img('heavy-pant-4036-black-back.jpg')],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in black. Style 4036. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4036', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Heavy Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '21',
    handle: 'heavy-pant-4036-olive',
    name: 'Bolster Heavy Pant — Olive',
    styleNo: '4036',
    price: 1699,
    categories: ['pants'],
    images: [img('heavy-pant-4036-olive-front.jpg'), img('heavy-pant-4036-olive-back.jpg')],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in olive. Style 4036. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4036', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Heavy Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '22',
    handle: 'comfort-pant-4038-cream',
    name: 'Bolster Comfort Pant — Cream',
    styleNo: '4038',
    price: 1699,
    categories: ['pants'],
    images: [img('comfort-pant-4038-cream-front.jpg'), img('comfort-pant-4038-cream-back.jpg')],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in cream. Style 4038. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4038', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Comfort Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Cream',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '23',
    handle: 'comfort-pant-4038-black',
    name: 'Bolster Comfort Pant — Black',
    styleNo: '4038',
    price: 1699,
    categories: ['pants'],
    popular: true,
    images: [img('comfort-pant-4038-black-front.jpg'), img('comfort-pant-4038-black-back.jpg')],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in black. Style 4038. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4038', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Comfort Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '24',
    handle: 'comfort-pant-4038-beige',
    name: 'Bolster Comfort Pant — Beige',
    styleNo: '4038',
    price: 1699,
    categories: ['pants'],
    images: [img('comfort-pant-4038-beige-front.jpg'), img('comfort-pant-4038-beige-back.jpg')],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in beige. Style 4038. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4038', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Comfort Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Beige',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '25',
    handle: 'comfort-pant-4038-khaki',
    name: 'Bolster Comfort Pant — Khaki',
    styleNo: '4038',
    price: 1699,
    categories: ['pants'],
    images: [img('comfort-pant-4038-khaki-front.jpg'), img('comfort-pant-4038-khaki-back.jpg')],
    description:
      'An easy comfort-fit trouser in 100% cotton, finished in khaki. Style 4038. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 4038', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Breathable', 'Comfort', 'Timeless', 'Relaxed', 'Effortless'],
    type: 'Comfort Pant',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Khaki',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '26',
    handle: 'corduroy-shirt-0041-beige',
    name: 'Corduroy Shirt — Beige',
    styleNo: '0041',
    price: 1499,
    categories: ['shirts'],
    popular: true,
    images: [img('corduroy-shirt-0041-beige-front.jpg'), img('corduroy-shirt-0041-beige-back.jpg')],
    description:
      'A corduroy shirt in 98% cotton 2% spandex, finished in beige. Style 0041. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0041', '98% Cotton 2% Spandex', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    color: 'Beige',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '27',
    handle: 'corduroy-shirt-0040-fawn',
    name: 'Corduroy Shirt 0040 — Fawn',
    styleNo: '0040',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-0040-fawn-front.jpg'), img('corduroy-shirt-0040-fawn-back.jpg')],
    description:
      'A corduroy shirt in 98% cotton 2% spandex, finished in fawn. Style 0040. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0040', '98% Cotton 2% Spandex', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    color: 'Fawn',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '28',
    handle: 'corduroy-shirt-0039-olive',
    name: 'Corduroy Shirt 0039 — Olive',
    styleNo: '0039',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-0039-olive-front.jpg'), img('corduroy-shirt-0039-olive-back.jpg')],
    description:
      'A corduroy shirt in 98% cotton 2% spandex, finished in olive. Style 0039. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0039', '98% Cotton 2% Spandex', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '29',
    handle: 'denim-shirt-0038-black',
    name: 'Denim Shirt 0038 — Black',
    styleNo: '0038',
    price: 1499,
    categories: ['shirts'],
    images: [
      img('denim-shirt-0038-black-front.jpg'),
      img('denim-shirt-0038-black-back.jpg'),
      img('denim-shirt-0038-black-detail.jpg'),
    ],
    description:
      'A denim shirt in 100% cotton lined in anti pill fleece, finished in black. Style 0038. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0038', '100% Cotton', 'Regular fit', 'Anti Pill Fleece lining', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '30',
    handle: 'denim-shirt-0043-ice-berg',
    name: 'Denim Shirt — Ice Berg',
    styleNo: '0043',
    price: 1499,
    categories: ['shirts'],
    popular: true,
    images: [img('denim-shirt-0043-ice-berg-front.jpg'), img('denim-shirt-0043-ice-berg-back.jpg')],
    description:
      'A denim shirt in 100% cotton, finished in ice berg. Style 0043. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0043', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Ice Berg',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '31',
    handle: 'denim-shirt-0044-black',
    name: 'Denim Shirt 0044 — Black',
    styleNo: '0044',
    price: 1499,
    categories: ['shirts'],
    images: [img('denim-shirt-0044-black-front.jpg'), img('denim-shirt-0044-black-back.jpg')],
    description:
      'A denim shirt in 100% cotton, finished in black. Style 0044. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0044', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '32',
    handle: 'denim-shirt-0027-blue-ocean',
    name: 'Denim Shirt — Blue Ocean',
    styleNo: '0027',
    price: 1499,
    categories: ['shirts'],
    images: [
      img('denim-shirt-0027-blue-ocean-front.jpg'),
      img('denim-shirt-0027-blue-ocean-back.jpg'),
    ],
    description:
      'A denim shirt in 98% cotton 2% spandex, finished in blue ocean. Style 0027. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0027', '98% Cotton 2% Spandex', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    color: 'Blue Ocean',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '33',
    handle: 'denim-shirt-0024-dark-blue',
    name: 'Denim Shirt — Dark Blue',
    styleNo: '0024',
    price: 1499,
    categories: ['shirts'],
    images: [img('denim-shirt-0024-dark-blue-front.jpg'), img('denim-shirt-0024-dark-blue-back.jpg')],
    description:
      'A denim shirt in 98% cotton 2% spandex, finished in dark blue. Style 0024. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0024', '98% Cotton 2% Spandex', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    color: 'Dark Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '34',
    handle: 'denim-shirt-0023-icy-blue',
    name: 'Denim Shirt — Icy Blue',
    styleNo: '0023',
    price: 1499,
    categories: ['shirts'],
    images: [img('denim-shirt-0023-icy-blue-front.jpg'), img('denim-shirt-0023-icy-blue-back.jpg')],
    description:
      'A denim shirt in 100% cotton, finished in icy blue. Style 0023. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0023', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Icy Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '35',
    handle: 'denim-shirt-0042-washed-blue',
    name: 'Denim Shirt — Washed Blue',
    styleNo: '0042',
    price: 1499,
    categories: ['shirts'],
    images: [
      img('denim-shirt-0042-washed-blue-front.jpg'),
      img('denim-shirt-0042-washed-blue-back.jpg'),
    ],
    description:
      'A denim shirt in 100% cotton, finished in washed blue. Style 0042. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 0042', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Denim Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Washed Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '36',
    handle: 'corduroy-shirt-with-fleece-142-2-black',
    name: 'Corduroy Shirt With Fleece — Black',
    styleNo: '142-2',
    price: 1499,
    categories: ['shirts'],
    images: [
      img('corduroy-shirt-with-fleece-142-2-black-front.jpg'),
      img('corduroy-shirt-with-fleece-142-2-black-back.jpg'),
      img('corduroy-shirt-with-fleece-142-2-black-detail.jpg'),
    ],
    description:
      'A corduroy shirt with fleece in 100% cotton lined in anti pill fleece, finished in black. Style 142-2. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 142-2',
      '100% Cotton',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–3XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt With Fleece',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '37',
    handle: 'corduroy-shirt-with-fleece-142-1-beige',
    name: 'Corduroy Shirt With Fleece — Beige',
    styleNo: '142-1',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-with-fleece-142-1-beige-front.jpg')],
    description:
      'A corduroy shirt with fleece in 100% cotton lined in anti pill fleece, finished in beige. Style 142-1. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 142-1',
      '100% Cotton',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–3XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt With Fleece',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Beige',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '38',
    handle: 'corduroy-shirt-with-fleece-142-3-brown',
    name: 'Corduroy Shirt With Fleece — Brown',
    styleNo: '142-3',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-with-fleece-142-3-brown-front.jpg')],
    description:
      'A corduroy shirt with fleece in 100% cotton lined in anti pill fleece, finished in brown. Style 142-3. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 142-3',
      '100% Cotton',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–3XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt With Fleece',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Brown',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '39',
    handle: 'corduroy-shirt-with-fleece-142-4-navy',
    name: 'Corduroy Shirt With Fleece — Navy',
    styleNo: '142-4',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-with-fleece-142-4-navy-front.jpg')],
    description:
      'A corduroy shirt with fleece in 100% cotton lined in anti pill fleece, finished in navy. Style 142-4. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 142-4',
      '100% Cotton',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–3XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt With Fleece',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '40',
    handle: 'corduroy-shirt-with-fleece-142-6-wine',
    name: 'Corduroy Shirt With Fleece — Wine',
    styleNo: '142-6',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-with-fleece-142-6-wine-front.jpg')],
    description:
      'A corduroy shirt with fleece in 100% cotton lined in anti pill fleece, finished in wine. Style 142-6. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 142-6',
      '100% Cotton',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–3XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt With Fleece',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Wine',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '41',
    handle: 'corduroy-shirt-with-fleece-142-5-olive',
    name: 'Corduroy Shirt With Fleece — Olive',
    styleNo: '142-5',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-with-fleece-142-5-olive-front.jpg')],
    description:
      'A corduroy shirt with fleece in 100% cotton lined in anti pill fleece, finished in olive. Style 142-5. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 142-5',
      '100% Cotton',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–3XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt With Fleece',
    fit: 'Regular',
    material: '100% Cotton',
    lining: 'Anti Pill Fleece',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '42',
    handle: 'corduroy-shirt-141-fawn',
    name: 'Corduroy Shirt 141 — Fawn',
    styleNo: '141',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-141-fawn-front.jpg'), img('corduroy-shirt-141-fawn-back.jpg')],
    description:
      'A corduroy shirt in 100% cotton, finished in fawn. Style 141. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 141', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Fawn',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '43',
    handle: 'corduroy-shirt-141-2-wine',
    name: 'Corduroy Shirt — Wine',
    styleNo: '141-2',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-141-2-wine-front.jpg')],
    description:
      'A corduroy shirt in 100% cotton, finished in wine. Style 141-2. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 141-2', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Wine',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '44',
    handle: 'corduroy-shirt-141-black',
    name: 'Corduroy Shirt — Black',
    styleNo: '141',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-141-black-front.jpg')],
    description:
      'A corduroy shirt in 100% cotton, finished in black. Style 141. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 141', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '45',
    handle: 'corduroy-shirt-141-1-navy',
    name: 'Corduroy Shirt — Navy',
    styleNo: '141-1',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-141-1-navy-front.jpg')],
    description:
      'A corduroy shirt in 100% cotton, finished in navy. Style 141-1. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 141-1', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '46',
    handle: 'corduroy-shirt-141-3-brown',
    name: 'Corduroy Shirt — Brown',
    styleNo: '141-3',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-141-3-brown-front.jpg')],
    description:
      'A corduroy shirt in 100% cotton, finished in brown. Style 141-3. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 141-3', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Brown',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '47',
    handle: 'corduroy-shirt-141-4-olive',
    name: 'Corduroy Shirt 141-4 — Olive',
    styleNo: '141-4',
    price: 1499,
    categories: ['shirts'],
    images: [img('corduroy-shirt-141-4-olive-front.jpg')],
    description:
      'A corduroy shirt in 100% cotton, finished in olive. Style 141-4. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 141-4', '100% Cotton', 'Regular fit', 'Sizes S–3XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    tags: ['Soft', 'Structured', 'Everyday', 'Layerable'],
    type: 'Corduroy Shirt',
    fit: 'Regular',
    material: '100% Cotton',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '48',
    handle: 'corduroy-jacket-173-brown',
    name: 'Corduroy Jacket — Brown',
    styleNo: '173',
    price: 3299,
    categories: ['jackets'],
    popular: true,
    images: [
      img('corduroy-jacket-173-brown-front.jpg'),
      img('corduroy-jacket-173-brown-back.jpg'),
      img('corduroy-jacket-173-brown-detail.jpg'),
    ],
    description:
      'A corduroy jacket in 98% cotton 2% spandex, lined in fur, finished in brown. Style 173. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 173', '98% Cotton 2% Spandex', 'Regular fit', 'Fur lining', 'Sizes S–4XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Corduroy Jacket',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    lining: 'Fur',
    color: 'Brown',
    colorFamily: 'Browns',
    inStock: true,
  },
  {
    id: '49',
    handle: 'corduroy-jacket-171-black',
    name: 'Corduroy Jacket — Black',
    styleNo: '171',
    price: 3299,
    categories: ['jackets'],
    images: [
      img('corduroy-jacket-171-black-front.jpg'),
      img('corduroy-jacket-171-black-back.jpg'),
      img('corduroy-jacket-171-black-detail.jpg'),
    ],
    description:
      'A corduroy jacket in 98% cotton 2% spandex, lined in fur, finished in black. Style 171. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 171', '98% Cotton 2% Spandex', 'Regular fit', 'Fur lining', 'Sizes S–4XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Corduroy Jacket',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    lining: 'Fur',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '50',
    handle: 'corduroy-jacket-172-olive',
    name: 'Corduroy Jacket — Olive',
    styleNo: '172',
    price: 3299,
    categories: ['jackets'],
    images: [
      img('corduroy-jacket-172-olive-front.jpg'),
      img('corduroy-jacket-172-olive-back.jpg'),
      img('corduroy-jacket-172-olive-detail.jpg'),
    ],
    description:
      'A corduroy jacket in 98% cotton 2% spandex, lined in fur, finished in olive. Style 172. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 172', '98% Cotton 2% Spandex', 'Regular fit', 'Fur lining', 'Sizes S–4XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Corduroy Jacket',
    fit: 'Regular',
    material: '98% Cotton 2% Spandex',
    lining: 'Fur',
    color: 'Olive',
    colorFamily: 'Greens',
    inStock: true,
  },
  {
    id: '51',
    handle: 'denim-fur-jacket-167-dark-blue',
    name: 'Denim Fur Jacket — Dark Blue',
    styleNo: '167',
    price: 3299,
    categories: ['jackets'],
    images: [
      img('denim-fur-jacket-167-dark-blue-front.jpg'),
      img('denim-fur-jacket-167-dark-blue-back.jpg'),
      img('denim-fur-jacket-167-dark-blue-detail.jpg'),
    ],
    description:
      'A denim fur jacket in 80% cotton 18% polyester 2% elastane, lined in fur, finished in dark blue. Style 167. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 167',
      '80% Cotton 18% Polyester 2% Elastane',
      'Regular fit',
      'Fur lining',
      'Sizes S–4XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Denim Fur Jacket',
    fit: 'Regular',
    material: '80% Cotton 18% Polyester 2% Elastane',
    lining: 'Fur',
    color: 'Dark Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '52',
    handle: 'denim-fur-jacket-163-blue-skin',
    name: 'Denim Fur Jacket — Blue Skin',
    styleNo: '163',
    price: 3299,
    categories: ['jackets'],
    images: [
      img('denim-fur-jacket-163-blue-skin-front.jpg'),
      img('denim-fur-jacket-163-blue-skin-back.jpg'),
      img('denim-fur-jacket-163-blue-skin-detail.jpg'),
    ],
    description:
      'A denim fur jacket in 84% cotton 15% polyester 1% elastane, lined in fur, finished in blue skin. Style 163. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 163',
      '84% Cotton 15% Polyester 1% Elastane',
      'Regular fit',
      'Fur lining',
      'Sizes S–4XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Denim Fur Jacket',
    fit: 'Regular',
    material: '84% Cotton 15% Polyester 1% Elastane',
    lining: 'Fur',
    color: 'Blue Skin',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '53',
    handle: 'denim-fleece-jacket-169-moon-light',
    name: 'Denim Fleece Jacket — Moon Light',
    styleNo: '169',
    price: 3299,
    categories: ['jackets'],
    images: [
      img('denim-fleece-jacket-169-moon-light-front.jpg'),
      img('denim-fleece-jacket-169-moon-light-back.jpg'),
      img('denim-fleece-jacket-169-moon-light-detail.jpg'),
    ],
    description:
      'A denim fleece jacket in 77% cotton 22% polyester 1% elastane, lined in anti pill fleece, finished in moon light. Style 169. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 169',
      '77% Cotton 22% Polyester 1% Elastane',
      'Regular fit',
      'Anti Pill Fleece lining',
      'Sizes S–4XL',
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Denim Fleece Jacket',
    fit: 'Regular',
    material: '77% Cotton 22% Polyester 1% Elastane',
    lining: 'Anti Pill Fleece',
    color: 'Moon Light',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '54',
    handle: 'denim-jacket-152-coal-grey',
    name: 'Denim Jacket — Coal Grey',
    styleNo: '152',
    price: 3299,
    categories: ['jackets'],
    images: [img('denim-jacket-152-coal-grey-front.jpg'), img('denim-jacket-152-coal-grey-back.jpg')],
    description:
      'A denim jacket in 84% cotton 15% polyester 1% elastane, finished in coal grey. Style 152. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 152', '84% Cotton 15% Polyester 1% Elastane', 'Regular fit', 'Sizes S–4XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Denim Jacket',
    fit: 'Regular',
    material: '84% Cotton 15% Polyester 1% Elastane',
    color: 'Coal Grey',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '55',
    handle: 'denim-jacket-164-tinted-blue',
    name: 'Denim Jacket — Tinted Blue',
    styleNo: '164',
    price: 3299,
    categories: ['jackets'],
    popular: true,
    images: [
      img('denim-jacket-164-tinted-blue-front.jpg'),
      img('denim-jacket-164-tinted-blue-back.jpg'),
    ],
    description:
      'A denim jacket in 84% cotton 15% polyester 1% elastane, finished in tinted blue. Style 164. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 164', '84% Cotton 15% Polyester 1% Elastane', 'Regular fit', 'Sizes S–4XL'],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],
    tags: ['Layered', 'Lined', 'Sturdy', 'Seasonal'],
    type: 'Denim Jacket',
    fit: 'Regular',
    material: '84% Cotton 15% Polyester 1% Elastane',
    color: 'Tinted Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '56',
    handle: 'joggers-2001-black',
    name: 'Denim Jogger — Black',
    styleNo: '2001',
    price: 2199,
    categories: ['denim'],
    images: [img('joggers-2001-black-front.jpg'), img('joggers-2001-black-back.jpg')],
    description:
      'A comfort-leg jean in 86% cotton 10% polyester 4% elastane, finished in black. Style 2001. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 2001', '86% Cotton 10% Polyester 4% Elastane', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Joggers',
    fit: 'Comfort',
    material: '86% Cotton 10% Polyester 4% Elastane',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '57',
    handle: 'joggers-2003-tinted-indigo',
    name: 'Denim Jogger — Tinted Indigo',
    styleNo: '2003',
    price: 2199,
    categories: ['denim'],
    images: [img('joggers-2003-tinted-indigo-front.jpg'), img('joggers-2003-tinted-indigo-back.jpg')],
    description:
      'A comfort-leg jean in 79% cotton 15% polyester 6% elastane, finished in tinted indigo. Style 2003. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 2003', '79% Cotton 15% Polyester 6% Elastane', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Joggers',
    fit: 'Comfort',
    material: '79% Cotton 15% Polyester 6% Elastane',
    color: 'Tinted Indigo',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '58',
    handle: 'joggers-2002-indigo',
    name: 'Denim Jogger — Indigo',
    styleNo: '2002',
    price: 2199,
    categories: ['denim'],
    images: [img('joggers-2002-indigo-front.jpg'), img('joggers-2002-indigo-back.jpg')],
    description:
      'A comfort-leg jean in 79% cotton 15% polyester 6% elastane, finished in indigo. Style 2002. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 2002', '79% Cotton 15% Polyester 6% Elastane', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Joggers',
    fit: 'Comfort',
    material: '79% Cotton 15% Polyester 6% Elastane',
    color: 'Indigo',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '59',
    handle: 'brawny-5462-navy',
    name: 'Brawny Straight Jean — Navy',
    styleNo: '5462',
    price: 2199,
    categories: ['denim'],
    popular: true,
    images: [img('brawny-5462-navy-front.jpg'), img('brawny-5462-navy-back.jpg')],
    description:
      'A straight-leg jean in 56% cotton 40% polyester 4% spandex, finished in navy. Style 5462. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5462', '56% Cotton 40% Polyester 4% Spandex', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '56% Cotton 40% Polyester 4% Spandex',
    color: 'Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '60',
    handle: 'brawny-5461-black',
    name: 'Brawny Straight Jean 5461 — Black',
    styleNo: '5461',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5461-black-front.jpg'), img('brawny-5461-black-back.jpg')],
    description:
      'A straight-leg jean in 56% cotton 40% polyester 4% spandex, finished in black. Style 5461. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5461', '56% Cotton 40% Polyester 4% Spandex', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '56% Cotton 40% Polyester 4% Spandex',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '61',
    handle: 'brawny-5463-grey',
    name: 'Brawny Straight Jean — Grey',
    styleNo: '5463',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5463-grey-front.jpg'), img('brawny-5463-grey-back.jpg')],
    description:
      'A straight-leg jean in 56% cotton 40% polyester 4% spandex, finished in grey. Style 5463. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5463', '56% Cotton 40% Polyester 4% Spandex', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '56% Cotton 40% Polyester 4% Spandex',
    color: 'Grey',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '62',
    handle: 'brawny-5464-off-white',
    name: 'Brawny Straight Jean — Off-White',
    styleNo: '5464',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5464-off-white-front.jpg'), img('brawny-5464-off-white-back.jpg')],
    description:
      'A straight-leg jean in 56% cotton 40% polyester 4% spandex, finished in off-white. Style 5464. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5464', '56% Cotton 40% Polyester 4% Spandex', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '56% Cotton 40% Polyester 4% Spandex',
    color: 'Off-White',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '63',
    handle: 'brawny-5547-dark-indigo',
    name: 'Brawny Straight Jean — Dark Indigo',
    styleNo: '5547',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5547-dark-indigo-front.jpg'), img('brawny-5547-dark-indigo-back.jpg')],
    description:
      'A straight-leg jean in 56% cotton 40% polyester 4% spandex, finished in dark indigo. Style 5547. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5547', '56% Cotton 40% Polyester 4% Spandex', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '56% Cotton 40% Polyester 4% Spandex',
    color: 'Dark Indigo',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '64',
    handle: 'brawny-5484-black',
    name: 'Brawny Straight Jean 5484 — Black',
    styleNo: '5484',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5484-black-front.jpg'), img('brawny-5484-black-back.jpg')],
    description:
      'A straight-leg jean in 99% cotton 1% elastane, finished in black. Style 5484. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5484', '99% Cotton 1% Elastane', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '99% Cotton 1% Elastane',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '65',
    handle: 'brawny-5551-tinted-indigo',
    name: 'Brawny Straight Jean — Tinted Indigo',
    styleNo: '5551',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5551-tinted-indigo-front.jpg'), img('brawny-5551-tinted-indigo-back.jpg')],
    description:
      'A straight-leg jean in 74% cotton 24% polyester 2% spandex, finished in tinted indigo. Style 5551. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5551', '74% Cotton 24% Polyester 2% Spandex', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '74% Cotton 24% Polyester 2% Spandex',
    color: 'Tinted Indigo',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '66',
    handle: 'brawny-5549-dark-navy',
    name: 'Brawny Straight Jean — Dark Navy',
    styleNo: '5549',
    price: 2199,
    categories: ['denim'],
    images: [img('brawny-5549-dark-navy-front.jpg'), img('brawny-5549-dark-navy-back.jpg')],
    description:
      'A straight-leg jean in 75% cotton 23% polyester 2% elastane, finished in dark navy. Style 5549. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 5549', '75% Cotton 23% Polyester 2% Elastane', 'Straight fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Brawny',
    fit: 'Straight',
    material: '75% Cotton 23% Polyester 2% Elastane',
    color: 'Dark Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '67',
    handle: 'jazz-3214-mid-blue',
    name: 'Jazz Comfort Jean — Mid Blue',
    styleNo: '3214',
    price: 2199,
    categories: ['denim'],
    popular: true,
    images: [img('jazz-3214-mid-blue-front.jpg'), img('jazz-3214-mid-blue-back.jpg')],
    description:
      'A comfort-leg jean in 69% cotton 29% polyester 2% spandex, finished in mid blue. Style 3214. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 3214', '69% Cotton 29% Polyester 2% Spandex', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz',
    fit: 'Comfort',
    material: '69% Cotton 29% Polyester 2% Spandex',
    color: 'Mid Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '68',
    handle: 'jazz-3180-dark-blue',
    name: 'Jazz Comfort Jean — Dark Blue',
    styleNo: '3180',
    price: 2199,
    categories: ['denim'],
    images: [img('jazz-3180-dark-blue-front.jpg'), img('jazz-3180-dark-blue-back.jpg')],
    description:
      'A comfort-leg jean in 99% cotton 1% elastane, finished in dark blue. Style 3180. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 3180', '99% Cotton 1% Elastane', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz',
    fit: 'Comfort',
    material: '99% Cotton 1% Elastane',
    color: 'Dark Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '69',
    handle: 'jazz-3124-raw-wash',
    name: 'Jazz Comfort Jean — Raw Wash',
    styleNo: '3124',
    price: 2199,
    categories: ['denim'],
    images: [img('jazz-3124-raw-wash-front.jpg'), img('jazz-3124-raw-wash-back.jpg')],
    description:
      'A comfort-leg jean in 98% cotton 2% spandex, finished in raw wash. Style 3124. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 3124', '98% Cotton 2% Spandex', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz',
    fit: 'Comfort',
    material: '98% Cotton 2% Spandex',
    color: 'Raw Wash',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '70',
    handle: 'jazz-3200-tinted-indigo',
    name: 'Jazz Comfort Jean — Tinted Indigo',
    styleNo: '3200',
    price: 2199,
    categories: ['denim'],
    images: [img('jazz-3200-tinted-indigo-front.jpg'), img('jazz-3200-tinted-indigo-back.jpg')],
    description:
      'A comfort-leg jean in 100% cotton, finished in tinted indigo. Style 3200. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 3200', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Tinted Indigo',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '71',
    handle: 'jazz-3190-black',
    name: 'Jazz Comfort Jean — Black',
    styleNo: '3190',
    price: 2199,
    categories: ['denim'],
    images: [img('jazz-3190-black-front.jpg'), img('jazz-3190-black-back.jpg')],
    description:
      'A comfort-leg jean in 99% cotton 1% elastane, finished in black. Style 3190. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 3190', '99% Cotton 1% Elastane', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz',
    fit: 'Comfort',
    material: '99% Cotton 1% Elastane',
    color: 'Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '72',
    handle: 'jazz-3178-ice-berg',
    name: 'Jazz Comfort Jean — Ice Berg',
    styleNo: '3178',
    price: 2199,
    categories: ['denim'],
    images: [img('jazz-3178-ice-berg-front.jpg'), img('jazz-3178-ice-berg-back.jpg')],
    description:
      'A comfort-leg jean in 100% cotton, finished in ice berg. Style 3178. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 3178', '100% Cotton', 'Comfort fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz',
    fit: 'Comfort',
    material: '100% Cotton',
    color: 'Ice Berg',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '73',
    handle: 'rock-166-raw-wash',
    name: 'Rock Baggy Jean — Raw Wash',
    styleNo: '166',
    price: 2199,
    categories: ['denim'],
    images: [img('rock-166-raw-wash-front.jpg'), img('rock-166-raw-wash-back.jpg')],
    description:
      'A baggy-leg jean in 98% cotton 2% spandex, finished in raw wash. Style 166. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 166', '98% Cotton 2% Spandex', 'Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Rock',
    fit: 'Baggy',
    material: '98% Cotton 2% Spandex',
    color: 'Raw Wash',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '74',
    handle: 'rock-163-dark-navy',
    name: 'Rock Baggy Jean — Dark Navy',
    styleNo: '163',
    price: 2199,
    categories: ['denim'],
    images: [img('rock-163-dark-navy-front.jpg'), img('rock-163-dark-navy-back.jpg')],
    description:
      'A baggy-leg jean in 98% cotton 2% spandex, finished in dark navy. Style 163. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 163', '98% Cotton 2% Spandex', 'Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Rock',
    fit: 'Baggy',
    material: '98% Cotton 2% Spandex',
    color: 'Dark Navy',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '75',
    handle: 'rock-159-dark-indigo',
    name: 'Rock Baggy Jean — Dark Indigo',
    styleNo: '159',
    price: 2199,
    categories: ['denim'],
    images: [img('rock-159-dark-indigo-front.jpg'), img('rock-159-dark-indigo-back.jpg')],
    description:
      'A baggy-leg jean in 99% cotton 1% elastane, finished in dark indigo. Style 159. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 159', '99% Cotton 1% Elastane', 'Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Rock',
    fit: 'Baggy',
    material: '99% Cotton 1% Elastane',
    color: 'Dark Indigo',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '76',
    handle: 'hulk-32003-mid-blue',
    name: 'Hulk Super Baggy Jean — Mid Blue',
    styleNo: '32003',
    price: 2199,
    categories: ['denim'],
    popular: true,
    images: [img('hulk-32003-mid-blue-front.jpg'), img('hulk-32003-mid-blue-back.jpg')],
    description:
      'A super baggy-leg jean in 100% cotton, finished in mid blue. Style 32003. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 32003', '100% Cotton', 'Super Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Hulk',
    fit: 'Super Baggy',
    material: '100% Cotton',
    color: 'Mid Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '77',
    handle: 'hulk-32001-coal',
    name: 'Hulk Super Baggy Jean — Coal',
    styleNo: '32001',
    price: 2199,
    categories: ['denim'],
    images: [img('hulk-32001-coal-front.jpg'), img('hulk-32001-coal-back.jpg')],
    description:
      'A super baggy-leg jean in 100% cotton, finished in coal. Style 32001. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 32001', '100% Cotton', 'Super Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Hulk',
    fit: 'Super Baggy',
    material: '100% Cotton',
    color: 'Coal',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '78',
    handle: 'hulk-32004-ice-berg',
    name: 'Hulk Super Baggy Jean — Ice Berg',
    styleNo: '32004',
    price: 2199,
    categories: ['denim'],
    images: [img('hulk-32004-ice-berg-front.jpg'), img('hulk-32004-ice-berg-back.jpg')],
    description:
      'A super baggy-leg jean in 100% cotton, finished in ice berg. Style 32004. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 32004', '100% Cotton', 'Super Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Hulk',
    fit: 'Super Baggy',
    material: '100% Cotton',
    color: 'Ice Berg',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '79',
    handle: 'hulk-32002-dark-blue',
    name: 'Hulk Super Baggy Jean — Dark Blue',
    styleNo: '32002',
    price: 2199,
    categories: ['denim'],
    images: [img('hulk-32002-dark-blue-front.jpg'), img('hulk-32002-dark-blue-back.jpg')],
    description:
      'A super baggy-leg jean in 100% cotton, finished in dark blue. Style 32002. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 32002', '100% Cotton', 'Super Baggy fit', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Hulk',
    fit: 'Super Baggy',
    material: '100% Cotton',
    color: 'Dark Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '80',
    handle: 'jazz-with-fleece-033-mid-blue',
    name: 'Jazz With Fleece Comfort Jean — Mid Blue',
    styleNo: '033',
    price: 2199,
    categories: ['denim'],
    images: [
      img('jazz-with-fleece-033-mid-blue-front.jpg'),
      img('jazz-with-fleece-033-mid-blue-back.jpg'),
      img('jazz-with-fleece-033-mid-blue-detail.jpg'),
    ],
    description:
      'A comfort-leg jean in 75% cotton 23% polyester 2% elastane with a fleece lining, finished in mid blue. Style 033. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 033',
      '75% Cotton 23% Polyester 2% Elastane',
      'Comfort fit',
      'Fleece lining',
      'Sizes 30–44',
    ],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz With Fleece',
    fit: 'Comfort',
    material: '75% Cotton 23% Polyester 2% Elastane',
    lining: 'Fleece',
    color: 'Mid Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '81',
    handle: 'jazz-with-fleece-028-grease-black',
    name: 'Jazz With Fleece Comfort Jean — Grease Black',
    styleNo: '028',
    price: 2199,
    categories: ['denim'],
    images: [
      img('jazz-with-fleece-028-grease-black-front.jpg'),
      img('jazz-with-fleece-028-grease-black-back.jpg'),
    ],
    description:
      'A comfort-leg jean in 99% cotton 1% elastane with a fleece lining, finished in grease black. Style 028. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 028', '99% Cotton 1% Elastane', 'Comfort fit', 'Fleece lining', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz With Fleece',
    fit: 'Comfort',
    material: '99% Cotton 1% Elastane',
    lining: 'Fleece',
    color: 'Grease Black',
    colorFamily: 'Neutrals',
    inStock: true,
  },
  {
    id: '82',
    handle: 'jazz-with-fleece-031-blue-ridge',
    name: 'Jazz With Fleece Comfort Jean — Blue Ridge',
    styleNo: '031',
    price: 2199,
    categories: ['denim'],
    images: [
      img('jazz-with-fleece-031-blue-ridge-front.jpg'),
      img('jazz-with-fleece-031-blue-ridge-back.jpg'),
    ],
    description:
      'A comfort-leg jean in 74% cotton 24% polyester 2% spandex with a fleece lining, finished in blue ridge. Style 031. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 031',
      '74% Cotton 24% Polyester 2% Spandex',
      'Comfort fit',
      'Fleece lining',
      'Sizes 30–44',
    ],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz With Fleece',
    fit: 'Comfort',
    material: '74% Cotton 24% Polyester 2% Spandex',
    lining: 'Fleece',
    color: 'Blue Ridge',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '83',
    handle: 'jazz-with-fleece-18014-marvin-blue',
    name: 'Jazz With Fleece Comfort Jean — Marvin Blue',
    styleNo: '18014',
    price: 2199,
    categories: ['denim'],
    images: [
      img('jazz-with-fleece-18014-marvin-blue-front.jpg'),
      img('jazz-with-fleece-18014-marvin-blue-back.jpg'),
    ],
    description:
      'A comfort-leg jean in 74% cotton 24% polyester 2% spandex with a fleece lining, finished in marvin blue. Style 18014. Cut and sewn at our own workshop in Delhi.',
    details: [
      'Style no. 18014',
      '74% Cotton 24% Polyester 2% Spandex',
      'Comfort fit',
      'Fleece lining',
      'Sizes 30–44',
    ],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz With Fleece',
    fit: 'Comfort',
    material: '74% Cotton 24% Polyester 2% Spandex',
    lining: 'Fleece',
    color: 'Marvin Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
  {
    id: '84',
    handle: 'jazz-with-fleece-035-light-blue',
    name: 'Jazz With Fleece Comfort Jean — Light Blue',
    styleNo: '035',
    price: 2199,
    categories: ['denim'],
    images: [
      img('jazz-with-fleece-035-light-blue-front.jpg'),
      img('jazz-with-fleece-035-light-blue-back.jpg'),
      img('jazz-with-fleece-035-light-blue-detail.jpg'),
    ],
    description:
      'A comfort-leg jean in 98% cotton 2% spandex with a fleece lining, finished in light blue. Style 035. Cut and sewn at our own workshop in Delhi.',
    details: ['Style no. 035', '98% Cotton 2% Spandex', 'Comfort fit', 'Fleece lining', 'Sizes 30–44'],
    sizes: ['30', '32', '34', '36', '38', '40', '42', '44'],
    tags: ['Rope-Dyed', 'Worn-In', 'Everyday', 'Durable'],
    type: 'Jazz With Fleece',
    fit: 'Comfort',
    material: '98% Cotton 2% Spandex',
    lining: 'Fleece',
    color: 'Light Blue',
    colorFamily: 'Blues',
    inStock: true,
  },
]

export function getProductByHandle(handle: string): Product | undefined {
  return PRODUCTS.find((p) => p.handle === handle)
}

export function getProductsByCategory(category: string): Product[] {
  if (CATEGORIES.some((c) => c.slug === category)) {
    return PRODUCTS.filter((p) => p.categories.includes(category as Category))
  }
  /* Anything else (including bookmarked slugs that no longer exist)
     falls back to the full range. */
  return PRODUCTS
}

export function formatPrice(price: number): string {
  return `₹${price.toLocaleString('en-IN')}`
}
